version: '2'
services:
  wwwapp:
     container_name: aplikasiphp
     image: apphp:v1.0.0 
     restart: always
     volumes:
        -  ${PWD}/app:/var/www/app
     ports:
        - "80:80"
     links:
        - www:api-data

  www:
     container_name: aplikasiphp2
     image: new_app_php:v1.0.0 
     restart: always
     volumes:
        -  ${PWD}/app_new_image:/var/www/app
     ports:
        - "8003:80"

  api:
     container_name: aplikasinodejs
     image: appsample:v1.0.0 
     tty: true
     #command : pm2 start app.js --no-daemon --watch -i max --max-memory-restart 3G --merge-logs --log-date-format="YYYY-MM-DD HH:mm Z"
     restart: always
     volumes:
      -  ${PWD}/nodejs/aplikasi:/app
     ports:
        - "4000:8000"
        - "5000:9000"
