version: '2'
services:
  api:
     container_name: aplikasinodejs
     image: appsample:v1.0.0 
     tty: true
     #command : pm2 start app.js --no-daemon --watch -i max --max-memory-restart 3G --merge-logs --log-date-format="YYYY-MM-DD HH:mm Z"
     restart: always
     volumes:
      - ".:/app"
     ports:
        - "4000:8000"
        - "5000:9000"
